language: cpp
compiler:
  - gcc
#  - clang
sudo: required
dist: trusty
#branches:
#  only:
#    - master
#    - develop
before_script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake -DCMAKE_VERBOSE_MAKEFILE=ON ../src
script: make
