language: cpp
compiler:
  - gcc
  - clang
# trusty (14.04) is now used instead of precise (12.04)
sudo: required
dist: trusty
#branches:
#  only:
#    - master
#    - develop
before_script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake -DCMAKE_VERBOSE_MAKEFILE=ON ..
script: make
