version: '{build}'

#branches:
#  only:
#    - master
#    - develop
#    - /^v.*$/

os: Visual Studio 2015

environment:
  matrix:
    - Toolset: v140
#    - Toolset: v120
#    - Toolset: v110
#    - Toolset: v100

platform:
  - Win32
  - x64

configuration:
  - Release
  - Debug

matrix:
  fast_finish: true

build:
  verbosity: minimal

before_build:
  - ps: |
      Write-Output "Configuration: $env:CONFIGURATION"
      Write-Output "Platform: $env:PLATFORM"
      $generator = switch ($env:TOOLSET)
      {
        "v140" {"Visual Studio 14 2015"}
        "v120" {"Visual Studio 12 2013"}
        "v110" {"Visual Studio 11 2012"}
        "v100" {"Visual Studio 10 2010"}
      }
      if ($env:PLATFORM -eq "x64")
      {
        $generator = "$generator Win64"
      }

build_script:
  - ps: |
      if (($env:TOOLSET -eq "v100") -and ($env:PLATFORM -eq "x64"))
      {
        return
      }
      md _build -Force | Out-Null
      cd _build

      & cmake -G "$generator" -D CMAKE_BUILD_TYPE=$env:CONFIGURATION ../src
      if ($LastExitCode -ne 0) {
        throw "Exec: $ErrorMessage"
      }

      & cmake --build . --config $env:CONFIGURATION
      if ($LastExitCode -ne 0) {
        throw "Exec: $ErrorMessage"
      }

after_build:
  - ps: |
      if (($env:TOOLSET -eq "v100") -and ($env:PLATFORM -eq "x64"))
      {
        return
      }

      & cpack -G ZIP -C $env:CONFIGURATION
      if ($LastExitCode -ne 0) {
        throw "Exec: $ErrorMessage"
      }

      & Get-ChildItem .\*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
      if ($LastExitCode -ne 0) {
        throw "Exec: $ErrorMessage"
      }

test_script:
  - ps: |
      if (($env:Toolset -eq "v100") -and ($env:PLATFORM -eq "x64"))
      {
        return
      }

      & ctest -VV -C $env:CONFIGURATION
      if ($LastExitCode -ne 0) {
        throw "Exec: $ErrorMessage"
      }

deploy:
  - provider: GitHub
    auth_token:
      secure: j1h5g/0lsbNqWV8GvsjA/HQdUDxkiM3IyeSB221HvlBZZylb/sGoKvePcwojbgv0
    artifact: /find_seed-*\.zip/
    draft: false
    prerelease: false
    on:
      branch: /^v.*$/
      appveyor_repo_tag: true
      configuration: Release
      Toolset: v140
