#include <iostream>
#include "test_ds.hpp"

namespace {

    class TestDS3 : public TestDS
    {
    protected:
        TestDS3() {
            IFNAME1 = (char *)"hsa_mirbase_1.txt";
            IFNAME2 = (char *)"utr3.txt";
            OFNAME1 = (char *)"test_output_3.txt";
            OFNAME2 = (char *)"test_ds3.txt";
        }
    };

    TEST_F(TestDS3, mrna_fasta) {
        read_files();

        EXPECT_EQ(1u, length(mrna_ids));

        const char *id1 = "hg18_refGene NM_018214 range=chr6:53895551-53896878 5'pad=0 3'pad=0 "
                "revComp=FALSE strand=+ repeatMasking=none";
        EXPECT_STREQ(id1, seqan::toCString(mrna_ids[0]));

        EXPECT_EQ(1u, length(mrna_seqs));
        const char *seq1 = "AGUUUCACCUCCAAGUUUUACCUCCUGUGUCUUCCUCUGCUGUCGAGACG"
                "UUCCUGUCUGCUUCCCGGGAGCCUCACGUGCUCCUUGUCCUAACCAGCCC"
                "CCGCGCGCCAUCUUCCCGUGGAGUGUGGGGAAGCUGCUGUCUCCCAGGAA"
                "GUGCCUUACUCAUCCCGCAACCAGUCAGCGCACCAGUGGUCUCCCGGUGU"
                "GAUUUUUUUUUUUUUUAAUUUCAGUUGUUUGUAAUAAGUAGAAUACACUA"
                "CUGUAAACAUACGACCUUUGUUUUUGUCUUAUGUUGGGGUAAAGGAAAGC"
                "AGGAAGGGGAAUUUUUAUCCUCCUCCCUUCCGUAAAGUGCUGGGAUAUUU"
                "UGAAUCCCCCAAGUUCCCUUGGACCUACUGAUGAGAGAUAGUUUUAUGUA"
                "UGGGGAAAAAUGGAUACUUUUUAAACCUUUUUUGGCAGCUCAGAUGGUGU"
                "AAAUUUUAAAAUUUUGUAUAGGUAUUUCAUAACAAAAAUAUGUAUUUCUU"
                "UUUUGUUAUUUUAUCUUGAAAACGGUACAUAUUUUAGUAUUUGUGCAGAA"
                "AAACAAGUCCUAAAGUAUUUGUUUUUAUUUGUACCAUCCACUUGUGCCUU"
                "ACUGUAUCCUGUGUCAUGUCCAAUCAGUUGUAAACAAUGGCAUCUUUGAA"
                "CAGUGUGAUGAGAAUAGGAAUGUGGUGUUUUAAAGCAGUGUUGCAUUUUA"
                "AUCAGUAAUCUACCUGGUGGAUUUGUUUUUAACCAAAAAGAUGAAUUAUC"
                "AAUGAUUUGUAAUUAUAUCAGUUGAUUUUUUUUGAAAAGAUGAACCAAAG"
                "GAUUUGACUGCUAAUAUUUUAUUCCUUACACUUUUUUUCUGAAUAAGUCU"
                "CUCAUAAUGAGUGCAGUGUCAGACUGUGCCUACUCUGAUGGUAUGUGCCA"
                "UUUGUAAAAUAAAAUAGAGCAGAAAAACACAAAAAGAGAACACUGGUUCA"
                "GACAUUCAGUGGGCAAGUAAAUUAUGGACUGCAAAAUAAUGAUUUUUAUU"
                "CAAGAAAGCUUUAAAAGUUUUAUAUCCAGAUAUACAACCACAAUAAAGCA"
                "AAAUAACCUACUAUCAAAAUAGAAAUGUUGCUAUCUUUAUAAGUGCAAUU"
                "UAAUUUGUAAAUAGAGUUUGAAUCAAAGUAUCACAAAAUACUGCUUCAAG"
                "AUUUAAUUUUAAAUCUGCUAAUUUAAGGGAUAUUGGGAAAAGUUUUGGUG"
                "UGUUUCUGUUGAUUUCUUUUUUGUAUGCUGUGAUAAAAGAGAAAUGAAAA"
                "GUGCCAGUCACUGUGUGGUGUCUAGGAAAAUCAUAUAUAUUUUUUUCUCC"
                "AAGAAAUAAAUUCAUCCUGGACAUUGGC";
        EXPECT_STREQ(seq1, seqan::toCString((seqan::CharString)mrna_seqs[0]));
    }

    TEST_F(TestDS3, comp_ngram) {
        comp_ngram();
    }

    TEST_F(TestDS3, comp_bruteforce) {
        comp_bruteforce();
    }

    TEST_F(TestDS3, comp_horspool) {
        comp_horspool();
    }

    TEST_F(TestDS3, comp_suffixarray) {
        comp_suffixarray();
    }
}