#include <iostream>
#include "test_ds.hpp"

namespace {

    class U3006 : public TestDS
    {
    protected:
        U3006() {
            IFNAME1 = (char *)"mir_001.txt";
            IFNAME2 = (char *)"utr3_006.txt";
            OFNAME1 = (char *)"test_output_6.txt";
            OFNAME2 = (char *)"test_ds6.txt";
        }
    };

    TEST_F(U3006, mrna_fasta) {
        read_files();

        EXPECT_EQ(6u, length(mrna_ids));

        const char *id1 = "hg18_refgene test1_8mer";
        EXPECT_STREQ(id1, seqan::toCString(mrna_ids[0]));

        const char *id2 = "hg18_refgene test2_7mer-m8";
        EXPECT_STREQ(id2, seqan::toCString(mrna_ids[1]));

        const char *id3 = "hg18_refgene test3_7mer-a1";
        EXPECT_STREQ(id3, seqan::toCString(mrna_ids[2]));

        const char *id4 = "hg18_refgene test4_6mer1";
        EXPECT_STREQ(id4, seqan::toCString(mrna_ids[3]));

        const char *id5 = "hg18_refgene test5_6mer2";
        EXPECT_STREQ(id5, seqan::toCString(mrna_ids[4]));

        const char *id6 = "hg18_refgene test5_6mer3";
        EXPECT_STREQ(id6, seqan::toCString(mrna_ids[5]));

        EXPECT_EQ(6u, length(mrna_seqs));
        const char *seq1 = "CCCCCCCCCCCCCAGUGCCUUACCCCCCCCCCCCCCCCCCCCCCCCCCCC"
                "CCCCCCCCCCCUGGAAAAAACCUUAAAAAAUGUUUCCUCCAAAUCUGAUU"
                "UCAUUACAUUUCUGAAUUGUUGGGGUUUUUUUUGUUGUUUUGUUUUGUUU"
                "UGUAGAUGGAGUUUCACUUUUGUUGCCCAGGCUGGAGUGUAGUGGCGCGA"
                "UCUCGGCUCAGCCUCCCGAGUAGCUGGGAUUACAGGCAUGUGCCACCACG"
                "CCCGGCUAAUGUUUGUAUUUUUAGUAGAGACGGGGUUUCACCAUGUUGGU"
                "CAGGCUGGUCUCAAACUCCUGACCUCAGGUGAUCCGCCCACCUCAGCCUC"
                "CCAAAGUGCUGGGAUGACAGGUGUGAGCCACUGCGCCCAGCCUGAAUCAU"
                "UUCUUAUACCUUCUGACAGCCCAACUUCCAGAGGACAGCUCUGGGGUACU"
                "CGUUGGAUGUCUGUGAGUACCUGGUCAUACGGGUCAGUAGGGAUAAGAAU"
                "UGUCUCUGGGCUGAGGAAUUCUUCUGUUCUCUGGUUUCACCAGCGUUGGG"
                "UUUGCUCAUGUAAUGUGGUCACCAUACUCAAAUGGUGUCAUGGCUGAAGU"
                "UGGCCACCUUGCUUGAGGGACAAGUUGUUUAUGUAUCAGCUCUCUGCUGG"
                "GUCUCCCUUUCCAUGGCAAAUGGGCAGCUCCAUCCUCUUGACUCUUCUAA"
                "AUGCCCAAAAGAGGUGUCAUGCUUUGGGGGUACGAUGUUUAUACUCCGUA"
                "AAGAACAUACAAGGACAUUCACUGCUGAUUUUUUUUUUUGUUUGUUUGAG"
                "ACAGGGUCUCACUCUGUCGCUCAGGCUGGAGUGCAGUGAUGCAAUCUUGG"
                "CUCACUGCAACCUCCGCCUCUCAGGUUCAAGUGGUUCUCCUUCCUCAGCC"
                "UCCCAAGUAGCUGGGAUUACAGGCACCUACCACCAGGGCCAGCUAAUUUU"
                "UGUAUGUUUAGUAGAAACGGGGUUUCACCAUGUUGGCCAGGCUGUUCUCG"
                "AACUCCUGACCUCAGGUGAUCUGCCCGCCUCGGUCUCCCAAAGUGCUGGG"
                "AUUACAGGCAUGAGCCACUGCACCUGACCUGCUGAAUUGUUUAUAAUGGC"
                "AAGAAAUAGGAAACCCCCCAAUGUCUGUUGAACAGCUAUCACGUUGAACC"
                "ACGUGAAACUGCUGUUUUCUAGGCCAAAAAUGGUGAGCGAUCAUUUAUUU"
                "CAUGAUUCAACCUGAUACAUUUACAUAGUGCAAAACUGUGUCACAGUUUC"
                "AGGCUUUUAUGAGGAAAGCGUUUCUGUGUAGAAACUGGAAGCUGUUCAGG"
                "GCAUCGGCAGCUGAACCCUGCUCCGUUGGUCAGCGUUACUAUCAUCUCGG"
                "AUCAUAUGGAGCUCAUGUCAGCCGUGUGGGUGGCGGGUGCACAGAGACGG"
                "UCUGGAAGGAAACACGCGGAUCUGAACAGCAGUAAUCCUGGGGGAUACGG"
                "GGGUUGGGCUAGAUUACAGAGGGCUCAUUUUCUACGUCAUGUAUUUUAUG"
                "AUACUUGAAUUUUUUGAAAUGGGCAUUUAUUUUAUAACAUGUUAAAAUGU"
                "ACUUUUUAAAUUAAGUCAUUUUGUAAUAUUUGAAUUUUUACAUUUGUUGU"
                "ACAAUCAGGAAAAGCAAUAAAGAUUUUUCAAAAAUAG";
        EXPECT_STREQ(seq1, seqan::toCString((seqan::CharString)mrna_seqs[0]));

        const char *seq2 = "CCCCCCCCCCCCCAGUGUCUUCCCCCCCCCCCCCCCCCCCCCCCCCCCCC"
                "CCCCCCCCCCCUGGAAAAAACCUUAAAAAAUGUUUCCUCCAAAUCUGAUU"
                "UCAUUACAUUUCUGAAUUGUUGGGGUUUUUUUUGUUGUUUUGUUUUGUUU"
                "UGUAGAUGGAGUUUCACUUUUGUUGCCCAGGCUGGAGUGUAGUGGCGCGA"
                "UCUCGGCUCAGCCUCCCGAGUAGCUGGGAUUACAGGCAUGUGCCACCACG"
                "CCCGGCUAAUGUUUGUAUUUUUAGUAGAGACGGGGUUUCACCAUGUUGGU"
                "CAGGCUGGUCUCAAACUCCUGACCUCAGGUGAUCCGCCCACCUCAGCCUC"
                "CCAAAGUGCUGGGAUGACAGGUGUGAGCCACUGCGCCCAGCCUGAAUCAU"
                "UUCUUAUACCUUCUGACAGCCCAACUUCCAGAGGACAGCUCUGGGGUACU"
                "CGUUGGAUGUCUGUGAGUACCUGGUCAUACGGGUCAGUAGGGAUAAGAAU"
                "UGUCUCUGGGCUGAGGAAUUCUUCUGUUCUCUGGUUUCACCAGCGUUGGG"
                "UUUGCUCAUGUAAUGUGGUCACCAUACUCAAAUGGUGUCAUGGCUGAAGU"
                "UGGCCACCUUGCUUGAGGGACAAGUUGUUUAUGUAUCAGCUCUCUGCUGG"
                "GUCUCCCUUUCCAUGGCAAAUGGGCAGCUCCAUCCUCUUGACUCUUCUAA"
                "AUGCCCAAAAGAGGUGUCAUGCUUUGGGGGUACGAUGUUUAUACUCCGUA"
                "AAGAACAUACAAGGACAUUCACUGCUGAUUUUUUUUUUUGUUUGUUUGAG"
                "ACAGGGUCUCACUCUGUCGCUCAGGCUGGAGUGCAGUGAUGCAAUCUUGG"
                "CUCACUGCAACCUCCGCCUCUCAGGUUCAAGUGGUUCUCCUUCCUCAGCC"
                "UCCCAAGUAGCUGGGAUUACAGGCACCUACCACCAGGGCCAGCUAAUUUU"
                "UGUAUGUUUAGUAGAAACGGGGUUUCACCAUGUUGGCCAGGCUGUUCUCG"
                "AACUCCUGACCUCAGGUGAUCUGCCCGCCUCGGUCUCCCAAAGUGCUGGG"
                "AUUACAGGCAUGAGCCACUGCACCUGACCUGCUGAAUUGUUUAUAAUGGC"
                "AAGAAAUAGGAAACCCCCCAAUGUCUGUUGAACAGCUAUCACGUUGAACC"
                "ACGUGAAACUGCUGUUUUCUAGGCCAAAAAUGGUGAGCGAUCAUUUAUUU"
                "CAUGAUUCAACCUGAUACAUUUACAUAGUGCAAAACUGUGUCACAGUUUC"
                "AGGCUUUUAUGAGGAAAGCGUUUCUGUGUAGAAACUGGAAGCUGUUCAGG"
                "GCAUCGGCAGCUGAACCCUGCUCCGUUGGUCAGCGUUACUAUCAUCUCGG"
                "AUCAUAUGGAGCUCAUGUCAGCCGUGUGGGUGGCGGGUGCACAGAGACGG"
                "UCUGGAAGGAAACACGCGGAUCUGAACAGCAGUAAUCCUGGGGGAUACGG"
                "GGGUUGGGCUAGAUUACAGAGGGCUCAUUUUCUACGUCAUGUAUUUUAUG"
                "AUACUUGAAUUUUUUGAAAUGGGCAUUUAUUUUAUAACAUGUUAAAAUGU"
                "ACUUUUUAAAUUAAGUCAUUUUGUAAUAUUUGAAUUUUUACAUUUGUUGU"
                "ACAAUCAGGAAAAGCAAUAAAGAUUUUUCAAAAAUAG";
        EXPECT_STREQ(seq2, seqan::toCString((seqan::CharString)mrna_seqs[1]));

        const char *seq3 = "CCCCCCCCCCCCCAAUGUCUUACCCCCCCCCCCCCCCCCCCCCCCCCCCC"
                "CCCCCCCCCCCUGGAAAAAACCUUAAAAAAUGUUUCCUCCAAAUCUGAUU"
                "UCAUUACAUUUCUGAAUUGUUGGGGUUUUUUUUGUUGUUUUGUUUUGUUU"
                "UGUAGAUGGAGUUUCACUUUUGUUGCCCAGGCUGGAGUGUAGUGGCGCGA"
                "UCUCGGCUCAGCCUCCCGAGUAGCUGGGAUUACAGGCAUGUGCCACCACG"
                "CCCGGCUAAUGUUUGUAUUUUUAGUAGAGACGGGGUUUCACCAUGUUGGU"
                "CAGGCUGGUCUCAAACUCCUGACCUCAGGUGAUCCGCCCACCUCAGCCUC"
                "CCAAAGUGCUGGGAUGACAGGUGUGAGCCACUGCGCCCAGCCUGAAUCAU"
                "UUCUUAUACCUUCUGACAGCCCAACUUCCAGAGGACAGCUCUGGGGUACU"
                "CGUUGGAUGUCUGUGAGUACCUGGUCAUACGGGUCAGUAGGGAUAAGAAU"
                "UGUCUCUGGGCUGAGGAAUUCUUCUGUUCUCUGGUUUCACCAGCGUUGGG"
                "UUUGCUCAUGUAAUGUGGUCACCAUACUCAAAUGGUGUCAUGGCUGAAGU"
                "UGGCCACCUUGCUUGAGGGACAAGUUGUUUAUGUAUCAGCUCUCUGCUGG"
                "GUCUCCCUUUCCAUGGCAAAUGGGCAGCUCCAUCCUCUUGACUCUUCUAA"
                "AUGCCCAAAAGAGGUGUCAUGCUUUGGGGGUACGAUGUUUAUACUCCGUA"
                "AAGAACAUACAAGGACAUUCACUGCUGAUUUUUUUUUUUGUUUGUUUGAG"
                "ACAGGGUCUCACUCUGUCGCUCAGGCUGGAGUGCAGUGAUGCAAUCUUGG"
                "CUCACUGCAACCUCCGCCUCUCAGGUUCAAGUGGUUCUCCUUCCUCAGCC"
                "UCCCAAGUAGCUGGGAUUACAGGCACCUACCACCAGGGCCAGCUAAUUUU"
                "UGUAUGUUUAGUAGAAACGGGGUUUCACCAUGUUGGCCAGGCUGUUCUCG"
                "AACUCCUGACCUCAGGUGAUCUGCCCGCCUCGGUCUCCCAAAGUGCUGGG"
                "AUUACAGGCAUGAGCCACUGCACCUGACCUGCUGAAUUGUUUAUAAUGGC"
                "AAGAAAUAGGAAACCCCCCAAUGUCUGUUGAACAGCUAUCACGUUGAACC"
                "ACGUGAAACUGCUGUUUUCUAGGCCAAAAAUGGUGAGCGAUCAUUUAUUU"
                "CAUGAUUCAACCUGAUACAUUUACAUAGUGCAAAACUGUGUCACAGUUUC"
                "AGGCUUUUAUGAGGAAAGCGUUUCUGUGUAGAAACUGGAAGCUGUUCAGG"
                "GCAUCGGCAGCUGAACCCUGCUCCGUUGGUCAGCGUUACUAUCAUCUCGG"
                "AUCAUAUGGAGCUCAUGUCAGCCGUGUGGGUGGCGGGUGCACAGAGACGG"
                "UCUGGAAGGAAACACGCGGAUCUGAACAGCAGUAAUCCUGGGGGAUACGG"
                "GGGUUGGGCUAGAUUACAGAGGGCUCAUUUUCUACGUCAUGUAUUUUAUG"
                "AUACUUGAAUUUUUUGAAAUGGGCAUUUAUUUUAUAACAUGUUAAAAUGU"
                "ACUUUUUAAAUUAAGUCAUUUUGUAAUAUUUGAAUUUUUACAUUUGUUGU"
                "ACAAUCAGGAAAAGCAAUAAAGAUUUUUCAAAAAUAG";
        EXPECT_STREQ(seq3, seqan::toCString((seqan::CharString)mrna_seqs[2]));

        const char *seq4 = "CCCCCCCCCCCCCAGUGCCUCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC"
                "CCCCCCCCCCCUGGAAAAAACCUUAAAAAAUGUUUCCUCCAAAUCUGAUU"
                "UCAUUACAUUUCUGAAUUGUUGGGGUUUUUUUUGUUGUUUUGUUUUGUUU"
                "UGUAGAUGGAGUUUCACUUUUGUUGCCCAGGCUGGAGUGUAGUGGCGCGA"
                "UCUCGGCUCAGCCUCCCGAGUAGCUGGGAUUACAGGCAUGUGCCACCACG"
                "CCCGGCUAAUGUUUGUAUUUUUAGUAGAGACGGGGUUUCACCAUGUUGGU"
                "CAGGCUGGUCUCAAACUCCUGACCUCAGGUGAUCCGCCCACCUCAGCCUC"
                "CCAAAGUGCUGGGAUGACAGGUGUGAGCCACUGCGCCCAGCCUGAAUCAU"
                "UUCUUAUACCUUCUGACAGCCCAACUUCCAGAGGACAGCUCUGGGGUACU"
                "CGUUGGAUGUCUGUGAGUACCUGGUCAUACGGGUCAGUAGGGAUAAGAAU"
                "UGUCUCUGGGCUGAGGAAUUCUUCUGUUCUCUGGUUUCACCAGCGUUGGG"
                "UUUGCUCAUGUAAUGUGGUCACCAUACUCAAAUGGUGUCAUGGCUGAAGU"
                "UGGCCACCUUGCUUGAGGGACAAGUUGUUUAUGUAUCAGCUCUCUGCUGG"
                "GUCUCCCUUUCCAUGGCAAAUGGGCAGCUCCAUCCUCUUGACUCUUCUAA"
                "AUGCCCAAAAGAGGUGUCAUGCUUUGGGGGUACGAUGUUUAUACUCCGUA"
                "AAGAACAUACAAGGACAUUCACUGCUGAUUUUUUUUUUUGUUUGUUUGAG"
                "ACAGGGUCUCACUCUGUCGCUCAGGCUGGAGUGCAGUGAUGCAAUCUUGG"
                "CUCACUGCAACCUCCGCCUCUCAGGUUCAAGUGGUUCUCCUUCCUCAGCC"
                "UCCCAAGUAGCUGGGAUUACAGGCACCUACCACCAGGGCCAGCUAAUUUU"
                "UGUAUGUUUAGUAGAAACGGGGUUUCACCAUGUUGGCCAGGCUGUUCUCG"
                "AACUCCUGACCUCAGGUGAUCUGCCCGCCUCGGUCUCCCAAAGUGCUGGG"
                "AUUACAGGCAUGAGCCACUGCACCUGACCUGCUGAAUUGUUUAUAAUGGC"
                "AAGAAAUAGGAAACCCCCCAAUGUCUGUUGAACAGCUAUCACGUUGAACC"
                "ACGUGAAACUGCUGUUUUCUAGGCCAAAAAUGGUGAGCGAUCAUUUAUUU"
                "CAUGAUUCAACCUGAUACAUUUACAUAGUGCAAAACUGUGUCACAGUUUC"
                "AGGCUUUUAUGAGGAAAGCGUUUCUGUGUAGAAACUGGAAGCUGUUCAGG"
                "GCAUCGGCAGCUGAACCCUGCUCCGUUGGUCAGCGUUACUAUCAUCUCGG"
                "AUCAUAUGGAGCUCAUGUCAGCCGUGUGGGUGGCGGGUGCACAGAGACGG"
                "UCUGGAAGGAAACACGCGGAUCUGAACAGCAGUAAUCCUGGGGGAUACGG"
                "GGGUUGGGCUAGAUUACAGAGGGCUCAUUUUCUACGUCAUGUAUUUUAUG"
                "AUACUUGAAUUUUUUGAAAUGGGCAUUUAUUUUAUAACAUGUUAAAAUGU"
                "ACUUUUUAAAUUAAGUCAUUUUGUAAUAUUUGAAUUUUUACAUUUGUUGU"
                "ACAAUCAGGAAAAGCAAUAAAGAUUUUUCAAAAAUAG";
        EXPECT_STREQ(seq4, seqan::toCString((seqan::CharString)mrna_seqs[3]));

        const char *seq5 = "CCCCCCCCCCCCCAGUGUCUGUCCCCCCCCCCCCCCCCCCCCCCCCCCCC"
                "CCCCCCCCCCCUGGAAAAAACCUUAAAAAAUGUUUCCUCCAAAUCUGAUU"
                "UCAUUACAUUUCUGAAUUGUUGGGGUUUUUUUUGUUGUUUUGUUUUGUUU"
                "UGUAGAUGGAGUUUCACUUUUGUUGCCCAGGCUGGAGUGUAGUGGCGCGA"
                "UCUCGGCUCAGCCUCCCGAGUAGCUGGGAUUACAGGCAUGUGCCACCACG"
                "CCCGGCUAAUGUUUGUAUUUUUAGUAGAGACGGGGUUUCACCAUGUUGGU"
                "CAGGCUGGUCUCAAACUCCUGACCUCAGGUGAUCCGCCCACCUCAGCCUC"
                "CCAAAGUGCUGGGAUGACAGGUGUGAGCCACUGCGCCCAGCCUGAAUCAU"
                "UUCUUAUACCUUCUGACAGCCCAACUUCCAGAGGACAGCUCUGGGGUACU"
                "CGUUGGAUGUCUGUGAGUACCUGGUCAUACGGGUCAGUAGGGAUAAGAAU"
                "UGUCUCUGGGCUGAGGAAUUCUUCUGUUCUCUGGUUUCACCAGCGUUGGG"
                "UUUGCUCAUGUAAUGUGGUCACCAUACUCAAAUGGUGUCAUGGCUGAAGU"
                "UGGCCACCUUGCUUGAGGGACAAGUUGUUUAUGUAUCAGCUCUCUGCUGG"
                "GUCUCCCUUUCCAUGGCAAAUGGGCAGCUCCAUCCUCUUGACUCUUCUAA"
                "AUGCCCAAAAGAGGUGUCAUGCUUUGGGGGUACGAUGUUUAUACUCCGUA"
                "AAGAACAUACAAGGACAUUCACUGCUGAUUUUUUUUUUUGUUUGUUUGAG"
                "ACAGGGUCUCACUCUGUCGCUCAGGCUGGAGUGCAGUGAUGCAAUCUUGG"
                "CUCACUGCAACCUCCGCCUCUCAGGUUCAAGUGGUUCUCCUUCCUCAGCC"
                "UCCCAAGUAGCUGGGAUUACAGGCACCUACCACCAGGGCCAGCUAAUUUU"
                "UGUAUGUUUAGUAGAAACGGGGUUUCACCAUGUUGGCCAGGCUGUUCUCG"
                "AACUCCUGACCUCAGGUGAUCUGCCCGCCUCGGUCUCCCAAAGUGCUGGG"
                "AUUACAGGCAUGAGCCACUGCACCUGACCUGCUGAAUUGUUUAUAAUGGC"
                "AAGAAAUAGGAAACCCCCCAAUGUCUGUUGAACAGCUAUCACGUUGAACC"
                "ACGUGAAACUGCUGUUUUCUAGGCCAAAAAUGGUGAGCGAUCAUUUAUUU"
                "CAUGAUUCAACCUGAUACAUUUACAUAGUGCAAAACUGUGUCACAGUUUC"
                "AGGCUUUUAUGAGGAAAGCGUUUCUGUGUAGAAACUGGAAGCUGUUCAGG"
                "GCAUCGGCAGCUGAACCCUGCUCCGUUGGUCAGCGUUACUAUCAUCUCGG"
                "AUCAUAUGGAGCUCAUGUCAGCCGUGUGGGUGGCGGGUGCACAGAGACGG"
                "UCUGGAAGGAAACACGCGGAUCUGAACAGCAGUAAUCCUGGGGGAUACGG"
                "GGGUUGGGCUAGAUUACAGAGGGCUCAUUUUCUACGUCAUGUAUUUUAUG"
                "AUACUUGAAUUUUUUGAAAUGGGCAUUUAUUUUAUAACAUGUUAAAAUGU"
                "ACUUUUUAAAUUAAGUCAUUUUGUAAUAUUUGAAUUUUUACAUUUGUUGU"
                "ACAAUCAGGAAAAGCAAUAAAGAUUUUUCAAAAAUAG";
        EXPECT_STREQ(seq5, seqan::toCString((seqan::CharString)mrna_seqs[4]));

        const char *seq6 = "CCCCCCCCCCCCCAAUGUCUUCCCCCCCCCCCCCCCCCCCCCCCCCCCCC"
                "CCCCCCCCCCCUGGAAAAAACCUUAAAAAAUGUUUCCUCCAAAUCUGAUU"
                "UCAUUACAUUUCUGAAUUGUUGGGGUUUUUUUUGUUGUUUUGUUUUGUUU"
                "UGUAGAUGGAGUUUCACUUUUGUUGCCCAGGCUGGAGUGUAGUGGCGCGA"
                "UCUCGGCUCAGCCUCCCGAGUAGCUGGGAUUACAGGCAUGUGCCACCACG"
                "CCCGGCUAAUGUUUGUAUUUUUAGUAGAGACGGGGUUUCACCAUGUUGGU"
                "CAGGCUGGUCUCAAACUCCUGACCUCAGGUGAUCCGCCCACCUCAGCCUC"
                "CCAAAGUGCUGGGAUGACAGGUGUGAGCCACUGCGCCCAGCCUGAAUCAU"
                "UUCUUAUACCUUCUGACAGCCCAACUUCCAGAGGACAGCUCUGGGGUACU"
                "CGUUGGAUGUCUGUGAGUACCUGGUCAUACGGGUCAGUAGGGAUAAGAAU"
                "UGUCUCUGGGCUGAGGAAUUCUUCUGUUCUCUGGUUUCACCAGCGUUGGG"
                "UUUGCUCAUGUAAUGUGGUCACCAUACUCAAAUGGUGUCAUGGCUGAAGU"
                "UGGCCACCUUGCUUGAGGGACAAGUUGUUUAUGUAUCAGCUCUCUGCUGG"
                "GUCUCCCUUUCCAUGGCAAAUGGGCAGCUCCAUCCUCUUGACUCUUCUAA"
                "AUGCCCAAAAGAGGUGUCAUGCUUUGGGGGUACGAUGUUUAUACUCCGUA"
                "AAGAACAUACAAGGACAUUCACUGCUGAUUUUUUUUUUUGUUUGUUUGAG"
                "ACAGGGUCUCACUCUGUCGCUCAGGCUGGAGUGCAGUGAUGCAAUCUUGG"
                "CUCACUGCAACCUCCGCCUCUCAGGUUCAAGUGGUUCUCCUUCCUCAGCC"
                "UCCCAAGUAGCUGGGAUUACAGGCACCUACCACCAGGGCCAGCUAAUUUU"
                "UGUAUGUUUAGUAGAAACGGGGUUUCACCAUGUUGGCCAGGCUGUUCUCG"
                "AACUCCUGACCUCAGGUGAUCUGCCCGCCUCGGUCUCCCAAAGUGCUGGG"
                "AUUACAGGCAUGAGCCACUGCACCUGACCUGCUGAAUUGUUUAUAAUGGC"
                "AAGAAAUAGGAAACCCCCCAAUGUCUGUUGAACAGCUAUCACGUUGAACC"
                "ACGUGAAACUGCUGUUUUCUAGGCCAAAAAUGGUGAGCGAUCAUUUAUUU"
                "CAUGAUUCAACCUGAUACAUUUACAUAGUGCAAAACUGUGUCACAGUUUC"
                "AGGCUUUUAUGAGGAAAGCGUUUCUGUGUAGAAACUGGAAGCUGUUCAGG"
                "GCAUCGGCAGCUGAACCCUGCUCCGUUGGUCAGCGUUACUAUCAUCUCGG"
                "AUCAUAUGGAGCUCAUGUCAGCCGUGUGGGUGGCGGGUGCACAGAGACGG"
                "UCUGGAAGGAAACACGCGGAUCUGAACAGCAGUAAUCCUGGGGGAUACGG"
                "GGGUUGGGCUAGAUUACAGAGGGCUCAUUUUCUACGUCAUGUAUUUUAUG"
                "AUACUUGAAUUUUUUGAAAUGGGCAUUUAUUUUAUAACAUGUUAAAAUGU"
                "ACUUUUUAAAUUAAGUCAUUUUGUAAUAUUUGAAUUUUUACAUUUGUUGU"
                "ACAAUCAGGAAAAGCAAUAAAGAUUUUUCAAAAAUAG";
        EXPECT_STREQ(seq6, seqan::toCString((seqan::CharString)mrna_seqs[5]));
    }

    TEST_F(U3006, comp_ngram) {
        comp_ngram();
    }

    TEST_F(U3006, comp_bruteforce) {
        comp_bruteforce();
    }

    TEST_F(U3006, comp_horspool) {
        comp_horspool();
    }

    TEST_F(U3006, comp_suffixarray) {
        comp_suffixarray();
    }
}